sudo: false
language: python
python:
  - "3.8"
  - "3.9"
addons:
  postgresql: "9.4"
env:
  matrix:
    - DJANGO_VERSION="==3.1.5" DB="postgres"
# command to install dependencies
install:
  - pip install Django$DJANGO_VERSION flake8 coverage
  - pip install -e .[all]
# command to run tests
before_script:
  - psql -c 'CREATE DATABASE lazysignup;' -U postgres
script:
  - flake8 .
  - coverage run manage.py test --settings=lazysignup.tests.settings
  - coverage report --fail-under=98
  - psql -c 'DROP DATABASE IF EXISTS test_lazysignup;' -U postgres
  - coverage erase
  - coverage run manage.py test --settings=custom_user_tests.settings
  - coverage report --fail-under=98
branches:
  except:
    - 33-late-logins
